### PR TITLE
Relax activerecord dependency

### PR DESCRIPTION
**Pull request by richardvenneman**
Thanks for the gem!

In order to use this with the latest Rails release, I had to relax this dependency.

Please mind #3 before merging.

### CODE REVIEW

**Comment by rokumatsumoto** [comment]
Hi @y9v,

Can you review this PR?

Thanks!

**Comment by y9v** [comment]
hi @rokumatsumoto!

Sorry, but it makes no sense to review this PR, since this gem won't work with Rails 5.2. Why relaxing the version constraint, if your app will be broken afterwards?

This gem needs to be adapted first to AR 5.2, and relaxing the dependency is 0.1% of work that needs to be done.

**Comment by rokumatsumoto** [comment]
Hi @y9v,

Sorry, I thought you can make enough time to fix these issues, by the way, I managed to run it with this [fork](https://github.com/sorare/activerecord-jsonb-associations)

rails version: 5.2.3

Thanks!

**Comment by y9v** [comment]
@rokumatsumoto thank you, I will take a look into it!

I will try to make this gem work with rails 5.2.3 within next weeks

**Pull request closed without merging**
